## Vector arithmetic

In [9]:
import numpy as np

In [10]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

In [11]:
a+b

array([30, 60, 90])

In [12]:
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
a-b

array([10, 20, 30])

In [ ]:
a-c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
multi=a*b
print(multi)

[ 200  800 1800]


In [ ]:
div=a/b
print(div)

[2. 2. 2.]


In [ ]:
scalar=5

In [ ]:
list_a=[10,11, 12, 13, 14, 15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [ ]:
list_as_array=np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]


In [ ]:
scalar*list_a

[10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15]

In [ ]:
scalar*list_as_array

array([50, 55, 60, 65, 70, 75])